### ISSUE TITLE
How to configure it for macOS?

### ISSUE THREAD

**Issue by wojciech-kulik** [vimjoyer/nix-editor-setup-video#3]
Hi,

any advice on how to configure it for nix-darwn + home-manager? I can't figure it out :(

Here is my original issue:
https://github.com/nix-community/nixd/issues/608

**Comment by ircurry** [comment]
I'm not able to help you that much because I don't use neovim but I know there are plenty of people on the discord that would be willing to help you with this and may have already had this issue before (or something like it). This is the link to the discord: https://discord.gg/AqHbaeK43b

My guess from just looking at it (and I want to reiterate that I don't use neovim so this could very well be wrong) is the line that is double commented out uses a path with a tilde so you may want to try changing it to use an absolute path like `/home/user/my-repo/flake.nix`.

**Comment by wojciech-kulik** [comment]
Thank you, indeed it turned out that:
1. it must be an absolute path
2. it must point to a directory, not flake

But still I've got a problem with home-manager. I can't figure out what expression would point to options. Maybe you could help with that?

I tried:
```
nix-repl> (builtins.getFlake "github:nix-community/home-manager/master").darwinModules.default { lib = {}; pkgs = {}; config = {}; }
[1/1/2 copied (305.5/361.4 MiB), 56.9 MiB DL] fetching source from https://cache.nixos.org{
  config = «error: undefined variable 'mkMerge'»;
  imports = [ ... ];
}
```
But I don't see options anywhere.

---

Update: it turned out that nixd doesn't support home-manager as module yet :(
